# Generated by Django 4.2 on 2024-02-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTukO1L_x6ddY1WGWjmSRcTAaE4QLAG1J5Ah9ThP7ApEQ&s', max_length=500),
        ),
    ]
